### PR TITLE
Use context correctly

### PR DESCRIPTION
**Pull request by squeedee**
---
name: Pull request
about: Submit changes to the code

---

## Changes proposed by this PR

* Use reconciler context in subsequent async calls, all the way to the client.
* Remove redundant WithValues from context based logging

## Release Note

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- ~[ ] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`~
- [x] Removed non-atomic or `wip` commits
- ~[ ] Filled in the [Release Note](#Release-Note) section above~
- ~[ ] Modified the docs to match changes~

### CODE REVIEW

**Comment by cirocosta** [comment]
yayy nice! that's a lot of changes 😅  thanks for putting the work! **overall, lgtm!**

---


trying to follow the chain of `ctx` being propagated through the code, one thing that I noticed that seems a little off is how we pass from `cmd/main.go` down to `pkg/root`:

- here we're passing it via a struct field

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/cmd/cartographer/main.go#L54

- here we're consuming from the struct

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/pkg/root/root.go#L112-L113

that's not very usual, and discouraged - the idiomatic way of doing doing would be to pass it via the function instead, being the first argument of the list.


it's not something introduced in this PR, but, sounds somewhat appropriate to patch given the context (no pun intended) 😁  wdyt?

thx!

**Comment by cirocosta** [comment]
oh also, here

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/pkg/root/root.go#L68-L70

we should make `ctx` the first argument instead.

**Comment by cirocosta** [comment]
sorry, one more 😅  we're doing the right thing creating a context with an associated cancel function

https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/cmd/cartographer/main.go#L42-L44

but that will not by default lead to a proper smooth termination when a signal is sent (either us sending a SIGINT / SIGTERM to `make run`, or kubelet trying to stop the pod with SIGINT)

> _By default, a synchronous signal is converted into a run-time panic. A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit._

(from https://pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs)

i.e., despite passing the context to the right places, we're not being graceful at all.

controller-runtime provides a nice little utility for covering this though: https://github.com/kubernetes-sigs/controller-runtime/blob/4d10a0615b11507451ecb58bfd59f0f6ef313a29/pkg/manager/signals/signal.go#L26-L30

```go
// SetupSignalHandler registers for SIGTERM and SIGINT. A context is returned
// which is canceled on one of these signals. If a second signal is caught, the program
// is terminated with exit code 1.
func SetupSignalHandler() context.Context {
```

so, doing something like

```diff

-       if err = cmd.Execute(); err != nil {
+       if err = cmd.Execute(ctrl.SetupSignalHandler()); err != nil {
                panic(err)
        }
 }
```

we should see that after sending a signal, it actually exits gracefully:

```
^C{"level":"info","ts":1637262059.6318526,"logger":"controller.workload","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"info","ts":1637262059.63193,"logger":"controller.supply-chain","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"info","ts":1637262059.6319268,"logger":"controller.deliverable","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"info","ts":1637262059.6318586,"logger":"controller.delivery","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"info","ts":1637262059.6319535,"logger":"controller.runnable-service","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"info","ts":1637262059.6319625,"logger":"controller.delivery","msg":"All workers finished"}
{"level":"info","ts":1637262059.6319673,"logger":"controller.runnable-service","msg":"All workers finished"}
{"level":"info","ts":1637262059.6319716,"logger":"controller.deliverable","msg":"All workers finished"}
{"level":"info","ts":1637262059.631974,"logger":"controller.supply-chain","msg":"All workers finished"}
{"level":"info","ts":1637262059.6319742,"logger":"controller.workload","msg":"All workers finished"}
```

(without that context w/ proper signal handling, we don't have the messages above ^)

**Review by cirocosta — APPROVED** [review]
left a couple comments about some complementary changes that could go in together, but that's it! lgtm 😁

**Comment by squeedee** [comment]
> yayy nice! that's a lot of changes 😅 thanks for putting the work! **overall, lgtm!**
> 
> trying to follow the chain of `ctx` being propagated through the code, one thing that I noticed that seems a little off is how we pass from `cmd/main.go` down to `pkg/root`:
> 
> * here we're passing it via a struct field
> 
> https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/cmd/cartographer/main.go#L54
> 
> * here we're consuming from the struct
> 
> https://github.com/vmware-tanzu/cartographer/blob/1bd6074009be49c21f238aa96d54537912a2669e/pkg/root/root.go#L112-L113
> 
> that's not very usual, and discouraged - the idiomatic way of doing doing would be to pass it via the function instead, being the first argument of the list.
> 
> it's not something introduced in this PR, but, sounds somewhat appropriate to patch given the context (no pun intended) 😁 wdyt?
> 
> thx!

I agree but I don't think I want to wait to rebase against main again just to get this work in.

**Comment by squeedee** [comment]
Issue created: https://github.com/vmware-tanzu/cartographer/issues/361

**Pull request merged**
