### PR TITLE
Use latest for ytt

### PR DESCRIPTION
**Pull request by emmjohnson**
Co-authored-by: Marty Spiewak <mspiewak@vmare.com>

[PR requirements]: https://github.com/vmware-tanzu/cartographer/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

## Changes proposed by this PR

closes # 

## Release Note

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [ ] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [ ] Removed non-atomic or `wip` commits
- [ ] Filled in the [Release Note](#Release-Note) section above 
- [ ] Modified the docs to match changes

### CODE REVIEW

**Review by scothis — CHANGES_REQUESTED** [review]
While ytt has strong history of backwards compatible releases, that won't be true forever. Reproducible builds within cartographer is more important than having the latest bits.

**Comment by martyspiewak** [comment]
@scothis The counter-pressure is that old versions of ytt have unpatched CVEs (due to the version of Go they are compiled with) that the later versions address.

As a compromise, do you think it'd be ok to pin to a major version of ytt? Is it fair to assume that if there is a breaking change they would bump major versions? We are talking about moving to using the ytt library instead of the binary (#526) and so we could use dependabot to pin to major versions but still get updates.

**Comment by scothis** [comment]
>The counter-pressure is that old versions of ytt have unpatched CVEs (due to the version of Go they are compiled with) that the later versions address.

I agree with the motivation, I disagree with the implementation

> As a compromise, do you think it'd be ok to pin to a major version of ytt? 

There are a few principles that drive my thinking:
1. every build of Cartographer is pinned to a specific version of ytt, this is fundamental to reproducible builds.
2. changes to the version of ytt are PRed and tested (like every other dependency bump, you can use Dependabot)
3. release branches can stay on an older, more stable version of ytt (if there are CVEs in an incompatible version, we can take that up with the Carvel team)

**Comment by scothis** [comment]
Another option to solve the immediate issue of the go compiler version is to `go build` the ytt source at a specific version and use that as the binary.

As you called out, consuming as a library would also work. My initial spike adding ytt support for templates used ytt as a go module rather than an executable.

**Pull request closed without merging**
