### PR TITLE
Fix link for High Level diagram

### PR DESCRIPTION
**Pull request by davidmirror-ops**
Signed-off-by: David Espejo <daespejo@vmware.com>

Fix broken link for High Level diagram

### CODE REVIEW

**Comment by cirocosta** [comment]
Hi @davidmirror-ops , thanks for bringing it up! It's indeed broken right now:

Screen Shot 2021-09-27 at 2 46 41 PM

and indeed, the correct path is after `img` rather than `images`

```
$ find . -name "ownership*"
./content/docs/img/ownership-flow.png
```

but I believe this PR is not there juuuust yet

1. with the versioning and lack of use of absolute paths, the requests for `images` are carrying the version

```
Request URL: http://127.0.0.1:1313/docs/v0.0.6/images/ownership-flow.png
``` 

2. there are a couple other places to fix

```console
$ ag ownership
content/docs/v0.0.6/about.md
35:![Cartographer High Level Diagram](images/ownership-flow.png)

content/docs/v0.0.6/_index.md
39:![Cartographer High Level Diagram](images/ownership-flow.png)

content/docs/about.md
35:![Cartographer High Level Diagram](img/ownership-flow.png)

content/docs/_index.md
39:![Cartographer High Level Diagram](images/ownership-flow.png)
```

---

For `1`, I think the best approach is to make use of Hugo's static assets directory (https://gohugo.io/content-management/static-files/) and then make use of absolute references in the markdown.

wdyt?

thanks!

cc @DanieldeR

**Comment by davidmirror-ops** [comment]
Hey @cirocosta agreed!
Indeed I'm used to doing it that way (paths relative to the static folder)

What would be the implications of that change?

**Comment by cirocosta** [comment]
I think the biggest implication would be that there wouldn't be a specific
diagram for each version, but rather a "global" one. I _think_ that's fine as I
believe that one is one that we do want to carry throughout versions, but I'll
ultimately defer to @DanieldeR 😁

**Comment by cirocosta** [comment]
thanks for submitting the changes @davidmirror-ops , it  looks like in https://github.com/vmware-tanzu/cartographer/commit/53e26861565b6c5cfa9ddeea75aeb2efe22e7add, @DanieldeR incorporated the changes 😁 closing this one then.

thank you!

**Pull request closed without merging**
