### PR TITLE
Fix RBAC errors in basic-delivery example

### LINKED ISSUE #674: Example "basic-delivery" is missing service account configuration
### Bug description:
Example `basic-delivery` uses the default service account in the namespace, which does not have access to certain necessary resources for successful completion of the Delivery.

### Steps to reproduce:
Deploy the basic-delivery example per the instructions. You should see errors saying certain resources cannot be accessed. For example the output of `kubectl describe deliverable gitops` might include:
```
    Message:               unable to apply object [default/gitops] for resource [source-provider] in delivery [deliver]: failed to get unstructured [default/gitops] from api server: gitrepositories.source.toolkit.fluxcd.io "gitops" is forbidden: User "system:serviceaccount:default:default" cannot get resource "gitrepositories" in API group "source.toolkit.fluxcd.io" in the namespace "default"
```

### Steps to fix:

The following service account configuration would suffice:
> Note: this proposal uses a conditional to create the service account if `data.values.ops_service_account_name` exists. This value would only need to be added to the `values.yaml` for the `basic-delivery` example.
```
#@ load("@ytt:data", "data")

#
# The service-account is referenced by the deliverable and provides permissions for
# Cartographer to create templated objects
#
#@ if hasattr(data.values, "ops_service_account_name"):
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.ops_service_account_name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deliverable-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deliverable-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.ops_service_account_name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deliverable-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kappctrl.k14s.io
      - serving.knative.dev
      - ""
    resources:
      - gitrepositories
      - apps
      - services
      - configmaps
      - pods
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
```

There are probably a few ways to approach this, but referencing the new service account in the Deliverable and in the kappctrl App configuration will work:

```
$ git diff examples/basic-delivery/app-operator/deliverable.yaml
diff --git a/examples/basic-delivery/app-operator/deliverable.yaml b/examples/basic-delivery/app-operator/deliverable.yaml
index 00c2dd0..b3d91ef 100644
--- a/examples/basic-delivery/app-operator/deliverable.yaml
+++ b/examples/basic-delivery/app-operator/deliverable.yaml
@@ -21,6 +21,7 @@ metadata:
   labels:
     app.tanzu.vmware.com/workload-type: deliver
 spec:
+  serviceAccountName: #@ data.values.ops_service_account_name
   source:
     git:
       url: #@ "ssh://git@" + data.values.git_writer.server + "/" + data.values.git_writer.repository
```

and

```
$ git diff examples/basic-delivery/app-operator/deploy-app.yaml
diff --git a/examples/basic-delivery/app-operator/deploy-app.yaml b/examples/basic-delivery/app-operator/deploy-app.yaml
index fec6bda..7897ae0 100644
--- a/examples/basic-delivery/app-operator/deploy-app.yaml
+++ b/examples/basic-delivery/app-operator/deploy-app.yaml
@@ -12,6 +12,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+#@ load("@ytt:data", "data")
+---
 apiVersion: carto.run/v1alpha1
 kind: ClusterDeploymentTemplate
 metadata:
@@ -32,7 +34,7 @@ spec:
     metadata:
       name: $(deliverable.metadata.name)$
     spec:
-      serviceAccountName: default
+      serviceAccountName: $(deliverable.spec.serviceAccountName)$
       fetch:
         - http:
             url: $(deployment.url)$
```

Some corresponding changes in the README for the basic-delivery example:
```
$ git diff examples/basic-delivery/README.md
diff --git a/examples/basic-delivery/README.md b/examples/basic-delivery/README.md
index 533a059..f3b912b 100644
--- a/examples/basic-delivery/README.md
+++ b/examples/basic-delivery/README.md
@@ -90,6 +90,7 @@ a kubernetes object written to it. (e.g. use the same values used in the [gitwri
 ---
 # configuration necessary for pushing the config to a git repository.
 #
+ops_service_account_name: cartographer-example-basic-delivery-sa
 git_writer:
   # the git server, for example gitlab.com
   server: github.com
@@ -125,7 +126,8 @@ kapp deploy --yes -a example \
   -f <(ytt --ignore-unknown-comments -f .) \
   -f <(ytt --ignore-unknown-comments -f ../shared/cluster/rbac.yaml -f ./values.yaml) \
   -f <(ytt --ignore-unknown-comments -f ../shared/cluster/secret.yaml -f ./values.yaml) \
-  -f <(ytt --ignore-unknown-comments -f ../shared/cluster/serviceaccount.yaml -f ./values.yaml)
+  -f <(ytt --ignore-unknown-comments -f ../shared/cluster/serviceaccount.yaml -f ./values.yaml) \
+  -f <(ytt --ignore-unknown-comments -f ../shared/app-operator/service-account.yaml -f ./values.yaml)  


@@ -276,7 +278,7 @@ spec:
     metadata:
       name: $(deliverable.metadata.name)$
     spec:
-      serviceAccountName: default
+      serviceAccountName: $(deliverable.spec.serviceAccountName)$
       fetch:
         - http:
```

### Expected behavior:
The Deliverable completes successfully, without errors about the default service account lacking access to any resources.

### Actual behavior:
The Deliverable fails and reports insufficient access to certain resources using the default service account.

### PR DESCRIPTION
**Pull request by ciberkleid**
Resolves RBAC errors in `examples/basic-delivery`:
- Error 1: Failing to get FluxCD GitRepository resources
- Error 2: Failing to get ConfigMaps resource

## Changes proposed by this PR

- Add `serviceAccountRef.name: #@ data.values.service_account_name` in ClusterDelivery (fixes error 1)
- Add Role and RoleBinding with missing permissions for Delivery (following approach used for `examples/gitwriter-sc`) and updating App.kappctrl.k14s.io definition in ClusterDeploymentTemplate to use `serviceAccountName: #@ data.values.service_account_name`

Closes #674

## Release Note

Fix RBAC errors in basic-delivery example

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [x ] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [x ] Removed non-atomic or `wip` commits
- [x ] Filled in the [Release Note](#Release-Note) section above 
- [ ] Modified the docs to match changes

### CODE REVIEW

**Review by martyspiewak — CHANGES_REQUESTED** [review]
Thanks for submitting this!

The only note I have is that we've tried to set the service account in the owner rather than the blueprint, so it would be a bit more consistent with the rest of the examples if you set `spec.serviceAccountName` in the deliverable, rather than `spec.serviceAccountRef.name` in the delivery. 

What do you think?

**Comment by ciberkleid** [comment]
On it! :)

**Comment by ciberkleid** [comment]
Made the suggested change, tested, and committed to the main branch in my fork. I'm not super knowledgeable about pull requests, so please let me know if there is anything more I need to do.

**Comment by martyspiewak** [comment]
Thanks for making the change!

It's failing the tests right now because there's one more thing to add: in `examples/basic-delivery/values.yaml` you just need to add `service_account_name: default`. So it should look like:
```
# Copyright 2021 VMware.....

#@data/values
---
git_writer:
  repository: github.com/example/example.git
  branch: main
service_account_name: default
```

**Comment by ciberkleid** [comment]
Interesting - thanks for the explanation! I actually don't use that
values file in my setup so I didn't catch that in my own testing. Fix is
pushed. Hopefully the tests pass now :)

**Review by martyspiewak — APPROVED** [review]
Thanks again for submitting!

**Pull request merged**
