### PR TITLE
Experiment/live editor

### PR DESCRIPTION
**Pull request by squeedee**
Live editor blog post, all in one repo.

[updates #566]

### CODE REVIEW

**Comment by squeedee** [comment]
I've reset the branch to where the code matches the published editor. Preview is now the correct version

**Comment by davidmirror-ops** [comment]
Thanks for this Rash

What I'm missing (and I think I saw in previous commits) is:

1. Instructions or keyboard shortcuts to show autocomplete, etc
2. Maybe it could be written more in a third-person voice. Right now it has several "I"'s which are fine and personal, but in terms of style, probably a third person format could be appropriate.

**Comment by squeedee** [comment]
@davidmirror-ops 
> 1. Instructions or keyboard shortcuts to show autocomplete, etc

The instructions are in the help on the editor page
I do have plans to put them in an accordion box so they're more obvious, but this is an early draft and I don't want to keep sinking effort into it. They are there, and I think more useful on the page than in the blog post

> 2. Maybe it could be written more in a third-person voice. Right now it has several "I"'s which are fine and personal, but in terms of style, probably a third person format could be appropriate.

I'm taking personal responsibility for this until it becomes formalized, so I feel this tone keeps it clear that folks will need to work with me (as the author of the page). Do you disagree?

**Review by davidmirror-ops — APPROVED** [review]

**Comment by davidmirror-ops** [comment]
/lgtm

Thanks Rash

**Review by zrob — APPROVED** [review]

**Pull request merged**
