### PR TITLE
Supply-chains refer to resources rather than components

### LINKED ISSUE #181: Rename 'components:' to 'resources:'
### Description of problem

We have a 'components:' block in the SupplyChain, which introduces a new concept 'components' that we don't really refer to anywhere else.

### Proposed solution

Let's simplify things and use 'resources:' instead.

### Example

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:                              #<=============== rename to resources
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: source-provider
          name: source

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image
```

### PR DESCRIPTION
**Pull request by waciumawanjohi**
Closes #181

Authored-by: Waciuma Wanjohi <lwanjohi@pivotal.io>

### CODE REVIEW

**Review by idoru — APPROVED** [review]

**Review by emmjohnson — APPROVED** [review]

**Comment by cirocosta** [comment]
I think it'd be great if we could capture some of these larger changes in a changlog - sure, when cutting a release we can always go back through history and make sure we annotate the important things, but I imagine it'd be easier to keep track of those as we PR these changes in. wdyt? (could be discussed elsewhere for sure)

**Comment by cirocosta** [comment]
uuf, a bunch of conflicts 😅 

Screen Shot 2021-10-12 at 7 32 33 AM

I think this is due to https://github.com/vmware-tanzu/cartographer/pull/196

**Comment by cirocosta** [comment]
ping @waciumawanjohi

**Comment by cirocosta** [comment]
~marked as _draft_ so we merge only after the 0.3 milestone so we get any breaking changes before GA but not in this release~ 

_0.3 it is!_

**Pull request closed without merging**
