### PR TITLE
Adds age and status to workload and ClusterSupplyChain CRDs

### LINKED ISSUE #90: Add age and status to CRDs.
From PR - https://github.com/vmware-tanzu/cartographer/pull/17

Ciro's comment - 
"I usually expect to see objects to share information about their age and current highest-level status, so I usually add"

```
+kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type==\"Ready\")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
```

"this is something we currently don't do for Workload and ClusterSupplyChain, but I think we should - makes the kubectl experience much better imo"

### PR DESCRIPTION
**Pull request by benjaminguttmann-avtq**
[PR requirements]: https://github.com/vmware-tanzu/cartographer/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

## Changes proposed by this PR

closes #90

## Release Note

Adds status and age information to Workload + ClusterSupplyChain CRD

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## PR Checklist

Note: Please do not remove items. Mark items as done `[x]` or use ~strikethrough~ if you believe they are not relevant

- [X] Linked to a relevant issue. Eg: `Fixes #123` or `Updates #123`
- [X] Removed non-atomic or `wip` commits
- [X] Filled in the [Release Note](#Release-Note) section above 
- ~~[ ] Modified the docs to match changes ~~

### CODE REVIEW

**Comment by emmjohnson** [comment]
Please rebase to get passing e2e tests - https://github.com/vmware-tanzu/cartographer/pull/630

**Comment by martyspiewak** [comment]
Thanks for submitting this! Would you mind adding the same fields to ClusterDelivery, Deliverable, and Runnable so that all of our CRDs are consistent? Other than that, everything looks great!

**Review by martyspiewak — CHANGES_REQUESTED** [review]
Thanks for submitting this! Would you mind adding the same fields to ClusterDelivery, Deliverable, and Runnable so that all of our CRDs are consistent? Other than that, everything looks great!

**Comment by benjaminguttmann-avtq** [comment]
Hi @martyspiewak thanks for the feedback, I have added that information. Correct me if I am wrong but I think to really streamline the information we would need to add reason for the status as well to all of them, because I could see that some (that already had status in place) have also a column named reason.

**Comment by martyspiewak** [comment]
@benjaminguttmann-avtq Ya that's a great point. I think that'd be valuable to add as well- would you mind doing that in this PR?

**Review by martyspiewak — APPROVED** [review]
This all looks great! Thanks so much for pointing all these inconsistencies out and fixing them!

**Pull request merged**
